apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-apbv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uzkm-tenant/rhtap-demo-app/hacbs-test-project-apbv@sha256:b56da14f7fde26af09589ea62c341f346f0b6a1406c3ebe1bc828ce6f78d3427
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
