apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-apbv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uzkm-tenant/rhtap-demo-app/hacbs-test-project-apbv@sha256:9827fbcf187585fd8287690845ca704cdb26e390c680fe9870563b34f5b2a1d3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
