apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-apbv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-apbv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-apbv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-apbv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-apbv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uzkm-tenant/rhtap-demo-app/hacbs-test-project-apbv@sha256:b56da14f7fde26af09589ea62c341f346f0b6a1406c3ebe1bc828ce6f78d3427
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
